# tests/test_notebook.py
"""Tests for Jupyter notebook job type (Phase 5)."""
from pathlib import Path
import pytest


# ── Task defaults ─────────────────────────────────────────────────────────────

def test_notebook_in_task_pod_defaults():
    from slurmdeck.jobs import TASK_POD_DEFAULTS
    assert "notebook" in TASK_POD_DEFAULTS


def test_notebook_defaults_correct():
    from slurmdeck.jobs import resource_defaults
    from slurmdeck.slurm import NodeStats
    stats = NodeStats(state="MIXED", cpu_load=0.0, cpu_total=32, cpu_alloc=0,
                      mem_total_mb=62000, mem_alloc_mb=0, gpu_total=1, gpu_alloc=0,
                      shard_total=4, shard_alloc=0)
    d = resource_defaults("notebook", stats)
    assert d.gpu_shards == 1
    assert d.cpus == 8
    assert d.mem_gb == 14
    assert d.time_limit == "08:00:00"


# ── render_notebook_sbatch ────────────────────────────────────────────────────

def _nb_spec(**kwargs):
    from slurmdeck.jobs import JobSpec
    defaults = dict(
        job_name="notebook",
        partition="gpu",
        gpu_shards=1,
        cpus=8,
        mem_gb=32,
        time_limit="08:00:00",
        run_command="",
        task_type="notebook",
    )
    defaults.update(kwargs)
    return JobSpec(**defaults)


def test_notebook_sbatch_has_jupyter_launch(tmp_path):
    from slurmdeck.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec()
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder, port=8888)
    assert "jupyter lab" in script
    assert "--no-browser" in script
    assert "--ip=$SD_NODE_ADDR" in script
    assert "--port=$SD_PORT --port-retries=0" in script


def test_notebook_sbatch_binds_to_node_addr_not_loopback(tmp_path):
    """The notebook runs on a GPU compute node but users tunnel in through the
    login/gateway node — a *different* host. Binding to 127.0.0.1 (loopback)
    made Jupyter unreachable through the tunnel. It must bind to the node's
    SLURM NodeAddr (routable from the gateway) and forward the tunnel there,
    never to loopback or the public-facing 0.0.0.0."""
    from slurmdeck.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec()
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder, port=8888)
    # Resolves the node's reachable address at runtime …
    assert "SD_NODE_ADDR=" in script
    assert "NodeAddr=" in script
    # … binds the server to it …
    assert "--ip=$SD_NODE_ADDR" in script
    # … and the tunnel forwards to that address, not localhost.
    assert "-L $SD_PORT:$SD_NODE_ADDR:$SD_PORT" in script
    # Never exposed on all interfaces (public network).
    assert "0.0.0.0" not in script


def test_notebook_sbatch_prints_ssh_tunnel_hint(tmp_path):
    from slurmdeck.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec()
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder, port=8888,
                                    gateway_host="10.35.4.100", gateway_port=2225)
    assert "ssh" in script
    assert "10.35.4.100" in script
    assert "8888" in script
    assert "2225" in script


def test_notebook_sbatch_token_generated_at_runtime(tmp_path):
    from slurmdeck.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec()
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder)
    # Token must be generated by the job, not hardcoded in the script
    assert "JUPYTER_TOKEN" in script
    assert "secrets.token_hex" in script


def test_notebook_sbatch_uses_conda_env(tmp_path):
    from slurmdeck.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec(conda_env="/shared/envs/pytorch-2.7")
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder)
    assert "conda activate" in script
    assert "jupyter lab" in script


def test_notebook_sbatch_uses_container_image(tmp_path):
    from slurmdeck.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec(container_image="/shared/images/data-science.sif")
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder)
    assert "apptainer exec --nv" in script
    assert "jupyter lab" in script
    assert "conda activate" not in script


def test_notebook_sbatch_custom_port(tmp_path):
    from slurmdeck.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec()
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder, port=9000)
    assert "base = 9000" in script
    assert "9000" in script   # also appears in tunnel hint


def test_notebook_sbatch_has_sbatch_directives(tmp_path):
    from slurmdeck.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec()
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder)
    assert "#!/bin/bash" in script
    assert "#SBATCH --gres=shard:1" in script
    assert "#SBATCH --mem=32G" in script
    assert "#SBATCH --time=08:00:00" in script


def test_notebook_sbatch_self_heals_missing_jupyter(tmp_path):
    """A chosen env without JupyterLab must self-heal, not die with
    'jupyter: command not found' (the original notebook-job failure)."""
    from slurmdeck.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec(conda_env="/shared/envs/pytorch-2.7")
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder)
    assert "command -v jupyter" in script
    assert "pip install --user" in script and "jupyterlab" in script
    # The launch still happens after the guard.
    assert script.index("command -v jupyter") < script.index("jupyter lab")


def test_notebook_sbatch_no_self_heal_for_container(tmp_path):
    """Container images are expected to ship Jupyter; no pip self-heal there."""
    from slurmdeck.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec(container_image="/shared/images/data-science.sif")
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder)
    assert "pip install --user --quiet jupyterlab" not in script


def test_notebook_sbatch_emits_mail_directives_when_mail_user_set(tmp_path):
    from slurmdeck.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec(mail_user="dahamadmin@iit.ac.lk")
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder)
    assert "#SBATCH --mail-user=dahamadmin@iit.ac.lk" in script
    assert "#SBATCH --mail-type=" in script


def test_notebook_sbatch_no_mail_directives_without_mail_user(tmp_path):
    from slurmdeck.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec()
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder)
    assert "--mail-user" not in script


def test_tensorboard_sbatch_emits_mail_directives_when_mail_user_set(tmp_path):
    from slurmdeck.jobs import JobSpec, make_job_folder, render_tensorboard_sbatch
    spec = JobSpec(job_name="tensorboard", partition="gpu", gpu_shards=0, cpus=2,
                   mem_gb=8, time_limit="08:00:00", run_command="",
                   task_type="tensorboard", mail_user="dahamadmin@iit.ac.lk")
    folder = make_job_folder(str(tmp_path), spec)
    script = render_tensorboard_sbatch(spec, folder, "/shared/logs")
    assert "#SBATCH --mail-user=dahamadmin@iit.ac.lk" in script
    assert "#SBATCH --mail-type=" in script


def test_notebook_sbatch_tunnel_uses_dash_N(tmp_path):
    """-N flag must appear in the printed tunnel command so running it does not
    launch the TUI — without -N the SSH session auto-starts slurm-deck and
    the user sees the TUI instead of an idle tunnel."""
    from slurmdeck.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec()
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder, port=8888,
                                    gateway_host="gw.edu", gateway_port=2225)
    assert "-N -L" in script, "Tunnel command must include -N (no-shell) flag"
    assert "ssh -p 2225 -N" in script


def test_notebook_sbatch_prints_token_explicitly(tmp_path):
    """Token must be echoed before JupyterLab starts so users can copy it from
    the job log without hunting through JupyterLab verbose startup output."""
    from slurmdeck.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec()
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder)
    assert "Token: $JUPYTER_TOKEN" in script
    # Token echo must appear BEFORE the jupyter lab launch line
    assert script.index("Token: $JUPYTER_TOKEN") < script.index("jupyter lab")


def test_notebook_sbatch_prints_full_lab_url_with_token(tmp_path):
    """The browser URL must include /lab?token= so users can paste it directly.
    http://127.0.0.1:<port> alone requires a separate token step."""
    from slurmdeck.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec()
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder, port=8888)
    assert "/lab?token=$JUPYTER_TOKEN" in script
    assert "http://127.0.0.1:$SD_PORT/lab?token=$JUPYTER_TOKEN" in script


def test_notebook_sbatch_uses_identity_provider_token(tmp_path):
    from slurmdeck.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec()
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder)
    assert "--IdentityProvider.token=" in script
    assert "--ServerApp.token" not in script


def test_notebook_sbatch_terminal_opens_in_user_own_folder(tmp_path):
    """--ServerApp.root_dir scopes the file browser to the user's own folder,
    but JupyterLab terminals spawn in the server process's cwd, not root_dir.
    #SBATCH --chdir points the process at the job's per-run folder, so without
    an explicit cd, terminals opened there instead of the user's own space
    (reported live). The script must cd into SD_USER_ROOT before launch."""
    from slurmdeck.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec()
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder)
    assert 'cd "$SD_USER_ROOT"' in script
    # Must happen after SD_USER_ROOT is defined/created, and before launch.
    assert script.index('SD_USER_ROOT="/shared/users/$USER"') < script.index('cd "$SD_USER_ROOT"')
    assert script.index('cd "$SD_USER_ROOT"') < script.index("jupyter lab")


def test_notebook_sbatch_terminal_cd_also_applies_to_container(tmp_path):
    from slurmdeck.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec(container_image="/shared/images/data-science.sif")
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder)
    assert 'cd "$SD_USER_ROOT"' in script
    assert script.index('cd "$SD_USER_ROOT"') < script.index("apptainer exec")


def test_notebook_sbatch_token_echo_uses_double_quotes(tmp_path):
    from slurmdeck.jobs import make_job_folder, render_notebook_sbatch
    spec = _nb_spec()
    folder = make_job_folder(str(tmp_path), spec)
    script = render_notebook_sbatch(spec, folder)
    dq_token = chr(34) + "Token: " + chr(36) + "JUPYTER_TOKEN" + chr(34)
    sq_token = chr(39) + "Token: " + chr(36) + "JUPYTER_TOKEN" + chr(39)
    assert dq_token in script, "Token echo must use double quotes"
    assert sq_token not in script, "Token echo must not use single quotes"
    dq_url = chr(34) + "Then open in browser:"
    sq_url = chr(39) + "Then open in browser:"
    assert dq_url in script, "URL echo must use double quotes"
    assert sq_url not in script, "URL echo must not use single quotes"
